using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class MoneyManager : MonoBehaviour
{
    public double currentMoney; // the current amount of money
    public Text moneyText; // the UI Text to display the current money amount
    public double moneyPerSecond; // the amount of money generated per second
    public List<MoneyGenerator> moneyGenerators; // the list of money generators
    public Text generatorCountText; // the UI Text to display the number of money generators

    void Start()
    {
        // initialize the current money and update the money text
        currentMoney = 0;
        UpdateMoneyText();

        // start the money generation coroutine
        StartCoroutine(GenerateMoney());
    }

    IEnumerator GenerateMoney()
    {
        while (true)
        {
            // calculate the total money generated by all money generators
            double totalMoneyGenerated = 0;
            foreach (MoneyGenerator generator in moneyGenerators)
            {
                totalMoneyGenerated += generator.GetMoneyGeneratedPerSecond();
            }

            // add the total money generated to the current money
            currentMoney += totalMoneyGenerated * Time.deltaTime;

            // update the money text
            UpdateMoneyText();

            yield return null;
        }
    }

    void UpdateMoneyText()
    {
        // update the money text with the current money
        moneyText.text = "$" + currentMoney.ToString("F2");
    }

    public void AddMoney(double amount)
    {
        // add the given amount of money to the current money
        currentMoney += amount;

        // update the money text
        UpdateMoneyText();
    }

    public void AddGenerator(MoneyGenerator generator)
    {
        // add the generator to the list of money generators
        moneyGenerators.Add(generator);

        // update the generator count text
        UpdateGeneratorCountText();
    }

    public void RemoveGenerator(MoneyGenerator generator)
    {
        // remove the generator from the list of money generators
        moneyGenerators.Remove(generator);

        // update the generator count text
        UpdateGeneratorCountText();
    }

    void UpdateGeneratorCountText()
    {
        // update the generator count text with the number of money generators
        generatorCountText.text = "Generators: " + moneyGenerators.Count.ToString();
    }
}
